name: Windows

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: SysBot.NET.slnx

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore NuGet packages
      run: dotnet restore $env:Solution_Name

    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --configuration $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Publish WinForm
      run: dotnet publish SysBot.Pokemon.WinForms\SysBot.Pokemon.WinForms.csproj -c $env:Configuration -r win-x64 --self-contained true /p:PublishSingleFile=true
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload WinForm EXE
      uses: actions/upload-artifact@v7
      with:
        name: SysBot.Pokemon.WinForms-win-x64
        path: SysBot.Pokemon.WinForms\bin\${{ matrix.configuration }}\net10.0-windows\win-x64\publish\*.exe
